### ISSUE TITLE
Alpha Release checklist

### ISSUE THREAD

**Issue by alisnic** [alisnic/solargraph-arc#6]
- [x] - don't mock reading schema in spec
- [x] - make completion assertion assert returned data type
- [x] - add rails 6 sample project
- [x] - readme
- [x] debug script
- [x] report a problem issue template
- [x] - test on multiple ruby versions
- [x] gem
- [x] explicit and automatic generation of coverage
- [x] logging
- [ ] demo
- [x] rescue boundaries per-feature
- [x] yank pre-release versions
